---
# tasks file for server
- name: Update yum cache
  yum: update_cache=yes
  become: yes


- name: Download and install MySQL Community Repo
  yum:
    name: http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
    state: present

- name: Install MySQL Server
  yum:
    name: mysql-server
    state: present

- name: Install remi repo
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Enable remi-php80
  command: yum-config-manager --enable remi-php80

- name: Update yum
  yum: update_cache=yes


- name: Install Apache / PHP
  yum: name={{ item }} state=present
  become: yes
  with_items:
    - epel-release
    - yum-utils
    - httpd
    - php
    - php80
    - php80-php-fpm
    - php80-php-mysqlnd
    - MySQL-python

- name: Install firewall firewalld
  yum:
    name: firewalld
    state: present

- name: Enable firewall
  command: systemctl start firewalld

- name: Enable shh (fw)
  command: firewall-cmd --permanent --add-service=ssh

- name: Enable smtp (fw)
  command: firewall-cmd --permanent --add-service=smtp #enable smtp also we can enable other multiple services when needed (example)

- name: Enable https (fw)
  command: firewall-cmd --permanent --add-service=https

- name: Reload firewall with new attribute
  command: firewall-cmd --reload

#we can also enable vpn / vpc and do a service auditing / and tls encryption or ssl