---
- name: Start MySQL Server and enable it
  service: name=mysqld state=started enabled=yes

- name: Remove Test database if it exist.
  mysql_db: name=test state=absent

  #remove all anynomous user for improving security and clean unusable data
- name: Remove All Anonymous User Accounts
  mysql_user: name=” host_all=yes state=absent

- name: Create mysql database
  mysql_db: name={{ wp_mysql_db }} state=present
  become: yes
  #create user with the name and password provided in the config file
- name: Create mysql user
  mysql_user: 
    name={{ wp_mysql_user }} 
    password={{ wp_mysql_password }} 
    priv=*.*:ALL

  become: yes  